name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: npm

      - uses: workos/setup-socket-firewall@ca93dd8aa351f54f4729fe3377a9be23c631c25d
        with:
          token: ${{ secrets.PUBLIC_SOCKET_FIREWALL_TOKEN }}
          allow-external-fork-fallback: true

      - run: npm ci

      - run: npm run lint

      - run: npm run format:check

      - run: npm run typecheck

      - run: npm run build
